### ISSUE TITLE
unexpected decompiled source 

### ISSUE THREAD

**Issue by haoqian-hao** [thuml/depyf#13]
Hi all,

I try to get the compiled function followed by the PyTorch website. 
> https://pytorch.org/docs/stable/torch.compiler_deepdive.html
```python
https://pytorch.org/docs/stable/torch.compiler_deepdive.html
``` 
However, it pops an error 
```python 
    print(innermost_fn(__compiled_fn_0).__self__.code)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute '__self__'. 
```
According to https://zhuanlan.zhihu.com/p/653323189, I change the code to 
```python 
__compiled_fn_0 = globals().globals.get("__compiled_fn_0")
print(decompile(__compiled_fn_0._torchdynamo_orig_callable))
```
However, the output does not match the result from the article. 

My output
```python 
source code of __compiled_fn_0:
def inner(*args, **kwargs):
    nonlocal fn
    __temp_3 = {}
    __temp_3.update(kwargs)
    return fn(*args, **__temp_3)
```

Exception 
```python 
source code of __compiled_fn_0:
def forward(self, L_a_, L_b_):
    l_a_ = L_a_
    l_b_ = L_b_
    abs_1 = torch.abs(l_a_)
    add = abs_1 + 1
    abs_1 = None
    truediv = l_a_ / add
    l_a_ = None
    add = None
    sum_1 = l_b_.sum()
    l_b_ = None
    lt = sum_1 < 0
    sum_1 = None
    return truediv, lt
````
I am wondering if I did something wrong. 

Thank you.

**Comment by youkaichao** [comment]
Hi, thanks for your interest.

The problem you reported is a bug of PyTorch, and I have filed an issue there https://github.com/pytorch/pytorch/issues/121198 .

Meanwhile, the recommended way of using `depyf` is to follow our [readme](https://github.com/thuml/depyf) with context wrapper (`with depyf.prepare_debug("./dump_src_dir"):`), which will take care of many annoying details for you :)
