### ISSUE TITLE
Which files to set the breakpoints in?

### ISSUE THREAD

**Issue by vimarsh6739** [thuml/depyf#16]
Hi, I'm trying to use `depyf` on the following example(it is a simplified form of the README with only the eager backend).

```python
import torch
from torch import _dynamo as torchdynamo
from typing import List

@torch.compile(backend="eager")
def toy_example(a, b):
    x = a / (torch.abs(a) + 1)
    if b.sum() < 0:
        b = b * -1
    return x * b

def main():
    for _ in range(100):
        toy_example(torch.randn(10), torch.randn(10))

if __name__ == "__main__":
    import depyf
    with depyf.prepare_debug("./dump_src_dir"):
        main()
    with depyf.debug():
        main()
```

 It produces the following output in `./dump_src_dir`

```
➜  dump_src_dir ls
'__compiled_fn_0 Captured Graph 0.py'   full_code_for_toy_example_0.py                                        __transformed_code_1_for_torch_dynamo_resume_in_toy_example_at_8.py
'__compiled_fn_3 Captured Graph 0.py'   __transformed_code_0_for_torch_dynamo_resume_in_toy_example_at_8.py
'__compiled_fn_4 Captured Graph 0.py'   __transformed_code_0_for_toy_example.py
```

Which files am I supposed to set the breakpoints in? The code just falls through no matter where I set the breakpoint.

**Comment by youkaichao** [comment]
Hi, you can set break points in `__compiled_fn` and `__transformed_code`. Here is my screenshot with vscode:

<img width="1486" alt="image" src="https://github.com/thuml/depyf/assets/23236638/e3123106-4d33-4c67-8087-a4a5cdd41bb6">

Can you give more information about how you are debugging?

**Comment by youkaichao** [comment]
And here is another screenshot to hit breakpoint in `__compiled_fn`:

<img width="1454" alt="image" src="https://github.com/thuml/depyf/assets/23236638/302f6b29-20d0-48b8-befc-683a63a0b297">

**Comment by vimarsh6739** [comment]
Oh I see. Is it necessary to use VSCode/VS here? I'm manually setting the breakpoint after opening the file in vim (using `breakpoint()`).

**Comment by youkaichao** [comment]
Do you use `pdb` in vim? Sorry but I don't know how to use vim for debugging :( Not sure what would be wrong with vim.

**Comment by vimarsh6739** [comment]
Yes, I'm using `pdb`. `breakpoint()` implicitly calls `pdb.set_trace()` (according to the docs [here](https://docs.python.org/3/library/pdb.html)).

**Comment by youkaichao** [comment]
By "manually setting breakpoint", do you mean you modify the code to add `breakpoint()`? That would not work though. You need to set breakpoint using debuggers. You can use `pdb` `b file:line`.

**Comment by youkaichao** [comment]
These `*.py` files are not executed directly by Python. And the modification you made to them will not take any effect.

**Comment by vimarsh6739** [comment]
Oh ok, so if I want to use pdb, should I set a `breakpoint()` before calling `main()` in the `depyf.debug()` context window?

**Comment by vimarsh6739** [comment]
This seems to work. I'm closing this. Thank you for the quick response!

I essentially set a `breakpoint()` in the original code like this. 
```python
with depyf.debug():
    breakpoint()
    main()
```

**Comment by youkaichao** [comment]
Wow that's a good solution 👍

**Comment by youkaichao** [comment]
@vimarsh6739 I added a `breakpoint` inside `depyf.debug`, so you don't have to add one any more! In addition, the program does not ask for input, so `pdb` users should be happy now. Try it out!

**Comment by vimarsh6739** [comment]
I just pulled in the updates, and this seems to work! Thanks for this.
