### ISSUE TITLE
Can not get the guard & code through API "_torchdynamo_orig_callable".

### ISSUE THREAD

**Issue by LHY-24** [thuml/depyf#2]
Hello, i read this [tutorial](https://zhuanlan.zhihu.com/p/653323189) and reimplement the corresponding result according to the code in the tutorial.

But an error occurs when i run: 
```
cache_entries = _debug_get_cache_entry_list(toy_example._torchdynamo_orig_callable.__code__)
guard, code = cache_entries[0]
```

The error information is:
```
TypeError: cannot unpack non-iterable torch._C.dynamo.eval_frame.CacheEntryWrapper object
```

I try to solve this problem by using:
```
code = cache_entries[0].code
guard = cache_entries[0].check_fn
```

But i meet another problem when getting the guard:
```
File "/home/abc/anaconda3/envs/abc/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 21
    if (getattr(utils_device, 'CURRENT_DEVICE') == None):
    ^
IndentationError: expected an indented block
```

I wonder this bug may caused by the adjustment of PyTorch API, looking forward to your reply.

**Comment by youkaichao** [comment]
Which PyTorch version do you use?

According to the [documentation](https://pytorch.org/docs/main/torch.compiler_deepdive.html#how-to-inspect-artifacts-generated-by-torchdynamo), we recommend the following usage now:

```python
from torch._dynamo.eval_frame import _debug_get_cache_entry_list, innermost_fn
cache_entries = _debug_get_cache_entry_list(innermost_fn(toy_example))
```

Indeed it will bring some trouble because of PyTorch versions you use. I just add some features to PyTorch recently, and they might not be available in the version of PyTorch you use.

**Comment by LHY-24** [comment]
I use python3.9.17.

I try this method just now, but maybe it does not work either.
```
from torch._dynamo.eval_frame import _debug_get_cache_entry_list, innermost_fn
cache_entries = _debug_get_cache_entry_list(innermost_fn(toy_example))
```
![WX20231024-123237](https://github.com/thuml/depyf/assets/61965761/af5dda1c-b450-46bb-8b0a-60ad25b4e797)

**Comment by youkaichao** [comment]
Hi, I mean the **PyTorch version**.

**Comment by LHY-24** [comment]
Sorry, my torch version is:
'2.1.0.dev20230903+cu121'

**Comment by youkaichao** [comment]
Can you use PyTorch nightly?

It should be simple to set up:

```shell
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch-nightly -c nvidia
```

And please follow the latest [documentation](https://pytorch.org/docs/main/torch.compiler_deepdive.html#how-to-inspect-artifacts-generated-by-torchdynamo).

**Comment by LHY-24** [comment]
Ye, i adopt your method and get the result below, decompile(code) works well but decompile(guard) seems not work.

Maybe there are some other incompatible problems.

Python version: 3.11.5
Torch version: '2.2.0.dev20231023'

![WX20231024-153228](https://github.com/thuml/depyf/assets/61965761/b29b0404-1ebc-4917-b18e-20874d5e521c)

**Comment by youkaichao** [comment]
Please don't use `decompile(guard)`. The [documentation](https://pytorch.org/docs/main/torch.compiler_deepdive.html) uses:

```python
for code_part in guard.code_parts:
    print(code_part)
```

And I recommend using the [dump src](https://github.com/thuml/depyf#explain-torchcompile-in-source-code) way.

**Comment by LHY-24** [comment]
Ok, i got it. 

Thanks for replying!

**Comment by youkaichao** [comment]
And please give us a star if you find `depyf` is useful :)
