### ISSUE TITLE
[Bug]: depyf `prepare_debug` broken due to change in `lazy_format_graph_code`

### ISSUE THREAD

**Issue by tombousso** [thuml/depyf#32]
### Your current environment

Latest depyf + pytorch nightly

### 🐛 Describe the bug

When trying to use depyf, dynamo crashes with
```
torch._dynamo.exc.InternalTorchDynamoError: lazy_format_graph_code() got an unexpected keyword argument 'include_stride'
```

This is due to a change to the `lazy_format_graph_code` in nightly - the function now accepts kwargs
https://github.com/pytorch/pytorch/blob/038b927590669f9368e78dd6d91911d24635c27e/torch/fx/_utils.py#L9

https://github.com/thuml/depyf/blob/master/depyf/explain/patched_lazy_format_graph_code.py#L1

**Comment by youkaichao** [comment]
@tombousso thanks for your interest and timely report! Can you help me review #33 ?

**Comment by tombousso** [comment]
Yes, this seems to be fixed. Thanks!
