### ISSUE TITLE
DecompilationError: Failed to decompile resume_in_forward

### ISSUE THREAD

**Issue by tbaggu** [thuml/depyf#8]
[2024-01-18 10:31:13,376] torch._dynamo.convert_frame: [WARNING] To diagnose recompilation issues, see https://pytorch.org/docs/master/compile/troubleshooting.html.
DecompilationError: Failed to decompile resume_in_forward
DecompilationError: Failed to decompile forward
DecompilationError: Failed to decompile resume_in_forward
DecompilationError: Failed to decompile forward
DecompilationError: Failed to decompile instruction Instruction(opcode=114, opname='POP_JUMP_IF_FALSE', arg=254, argval=254, argrepr='', offset=238, starts_line=383, is_jump_target=False) in resume_in__prepare_4d_causal_attention_mask_for_sdpa
DecompilationError: Failed to decompile instruction Instruction(opcode=114, opname='POP_JUMP_IF_FALSE', arg=254, argval=254, argrepr='', offset=238, starts_line=383, is_jump_target=False) in resume_in__prepare_4d_causal_attention_mask_for_sdpa
DecompilationError: Failed to decompile instruction Instruction(opcode=114, opname='POP_JUMP_IF_FALSE', arg=230, argval=230, argrepr='', offset=48, starts_line=354, is_jump_target=False) in _prepare_4d_causal_attention_mask_for_sdpa
--- 298.4484417438507 pytorch with compile CPU seconds --
`from transformers import AutoTokenizer, MixtralForCausalLM
import torch._dynamo
import torch._dynamo as dynamo
from torch._functorch.aot_autograd import aot_module_simplified
model_id = "mistralai/Mixtral-8x7B-v0.1"
model = MixtralForCausalLM.from_pretrained(model_id)
tokenizer = AutoTokenizer.from_pretrained(model_id)

text = "Hello my name is"
inputs = tokenizer(text, return_tensors="pt")
start_time = time.time()
print("cpu.................")
fn_cpu = torch.compile(model)
with torch.no_grad():
    with depyf.prepare_debug("./dump_src_dir"):
        output_cpu = fn_cpu(**inputs)
print("--- %s pytorch with compile CPU seconds ---" % (time.time() - start_time))
torch._dynamo.reset()`

**Comment by youkaichao** [comment]
Thanks for your interest. We are looking into it.

**Comment by youkaichao** [comment]
@tbaggu sorry for the late reply. Can you provide your `depyf` version? Can you try the latest `depyf` version? Your code works from my side.

**Comment by codes-team** [comment]
> @tbaggu sorry for the late reply. Can you provide your `depyf` version? Can you try the latest `depyf` version? Your code works from my side.

sorry but i don't understand how to use it so can you Explain to me

**Comment by tbaggu** [comment]
Hi

Bit busy with other things, need time to reproduce the error

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by youkaichao** [comment]
Hi, I tried this code with the latest `depyf` ([f38884c](https://github.com/thuml/depyf/commit/f38884c9690144942fef3256339ae8f3ecd7fa56)) and pytorch 2.2.1 . The following code runs without a problem:

```python
from transformers import AutoTokenizer, MixtralForCausalLM
import torch._dynamo
import torch._dynamo as dynamo
from torch._functorch.aot_autograd import aot_module_simplified
model_id = "mistralai/Mixtral-8x7B-v0.1"
model = MixtralForCausalLM.from_pretrained(model_id)
tokenizer = AutoTokenizer.from_pretrained(model_id)

text = "Hello my name is"
inputs = tokenizer(text, return_tensors="pt")
import time
start_time = time.time()
print("cpu.................")
fn_cpu = torch.compile(model)
with torch.no_grad():
    import depyf
    with depyf.prepare_debug("./dump_src_dir"):
        output_cpu = fn_cpu(**inputs)
print("--- %s pytorch with compile CPU seconds ---" % (time.time() - start_time))
torch._dynamo.reset()
```

I'm going to close this issue. If you find any error from your side, please feel free to re-open with more details :)
